name: Build 64-bit Windows Binary
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: x86_64-w64-mingw32
    steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y make binutils autoconf automake autotools-dev libtool pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 autopoint libcppunit-dev libxml2-dev libgcrypt11-dev lzip

    - name: Download dependencies
      run: wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz https://zlib.net/zlib-1.2.11.tar.xz

    - name: Build dependencies
      run: |
        for f in *.tar.*z; do tar xf "$f"; done
        cd gmp-6.2.1
        sed -i 's/-O2/-Os/g' configure
        ./configure --disable-shared --enable-static --prefix=/usr/local/$HOST --host=$HOST --disable-cxx --enable-fat CFLAGS="-mtune=generic -Os -g0"
        sudo make -j2 install
        cd ../zlib-1.2.11
        sed -i 's/-O2/-Os/g' configure
        CC=$HOST-gcc AR=$HOST-ar LD=$HOST-ld RANLIB=$HOST-ranlib STRIP=$HOST-strip ./configure --prefix=/usr/local/$HOST --libdir=/usr/local/$HOST/lib --includedir=/usr/local/$HOST/include --static
        sudo make -j2 install
        cd ..
        sudo rm -rf *
    - uses: actions/checkout@v2
      with:
        repository: aria2/aria2
        fetch-depth: 0
    - name: Checkout the latest tag
      id: checkout
      run: |
        git checkout $(git describe --tags --abbrev=0)
        echo "::set-output name=tag::$(git describe --tags --abbrev=0 | grep -Po '\d.+$')"
    - name: Edit OptionHandlerFactory.cc
      run: sed -i 's/16,/64,/g' src/OptionHandlerFactory.cc
    - name: Build aria2
      run: |
        autoreconf -i
        sed -i 's/-O2/-Os/g' configure
        ./mingw-config
        make -j2
        $HOST-strip src/aria2c.exe
    - uses: actions/upload-artifact@v2
      with:
        name: aria2c-${{ steps.checkout.outputs.tag }}
        path: src/aria2c.exe
