name: Build 64-bit Windows Binary
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: x86_64-w64-mingw32
    steps:
    - name: Install packages
      run: |
        sudo apt install \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev \
          gcc-mingw-w64 \
          g++-mingw-w64 \
          libcppunit-dev \
          lzip
    - name: Download dependencies
      run: wget https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz https://zlib.net/zlib-1.3.1.tar.xz
    - name: Build dependencies for skylake
      env:
        host_cpu: skylake
      run: |
        for f in *.tar.xz; do tar xf "$f"; done
        cd gmp-6.3.0
        ./configure --disable-shared --enable-static --prefix=/usr/local/$HOST --host=$HOST --disable-cxx --enable-fat CFLAGS="-march=$host_cpu -Os -g0"
        sudo make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" install
        cd ../zlib-1.3.1
        CFLAGS="-march=$host_cpu -Os" CC=$HOST-gcc AR=$HOST-ar LD=$HOST-ld RANLIB=$HOST-ranlib STRIP=$HOST-strip ./configure --prefix=/usr/local/$HOST --libdir=/usr/local/$HOST/lib --includedir=/usr/local/$HOST/include --static
        sudo make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" install
        cd ..
        sudo rm -rf *
    - uses: actions/checkout@v4
    - name: Edit OptionHandlerFactory.cc
      run: sed -i 's/16,/64,/g' src/OptionHandlerFactory.cc
    - name: Build aria2 for skylake
      env:
        host_cpu: skylake
      run: |
        autoreconf -i
        CFLAGS="-march=$host_cpu -Os" CXXFLAGS="-march=$host_cpu -Os" ./mingw-config
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)"
        $HOST-strip src/aria2c.exe
    - uses: actions/upload-artifact@v4
      with:
        name: aria2c for skylake
        path: src/aria2c.exe
